### ISSUE TITLE
How does glance compare to the other frontends?

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/paraview-glance#109]
There is 
- paraview web (all web frontends together and server side rendering backend)
- visualizer (old jquery based and new react based web frontend to paraview(web))
- lightviz
- and now glance (vue based)

What are the goals of each project? Why so much fragmentation? Can you please give a roadmap on the web frontend site?
As far as I can see glance is vtk.js based whereas pv web visualizer depends also on server side rendering.

I want to rewrite my post processing module of my online FEA tool witthout server side rendering. What would be a good way to start?

**Comment by aylward** [comment]
Great question!  We'll make a page to address this, but in summary

* ParaViewWeb is a library of methods/widgets.

* ParaViewVisaulizer is a web front-end to a paraview server.

* ParaViewGlance is a pure javascript visualization application.

So, as implied by the above, each has a unique set of use cases / goals:
* ParaViewVisualizer can handle large data, offers server-side processing, can be run without locally downloading the data, and requires a paraview server to be running (which requires installing such a server, scaling it for the number of simultaneous users, etc).    
* ParaViewGlance can only handle "small" datasets, does not provide server-side processing, must have the data locally to visualize it, but does not require a paraview server (nothing needs to be "installed" to run it - but it does not require scaling considerations since each instance is self contained/local).

The roadmap has some interesting possibilities - including potentially creating a single "paraviewX" that could be run as a server client (ala ParaViewVisualizer) or that could run as a stand-alone app (ala paraViewGlance), but that is dependent on the evolving needs of ParaView users as well as the evolving capabilities of javascript/browser technologies.   For now, each will continue on the paths summarized above so that users can choose the tool that is most appropriate for their current task.

For your FEA tool, there are a few factors to consider.   If your data is centralized or your computation requires a centralized compute resource, then ParaView(web) is still your best bet.    If your data is local and computation is "modest", you have options.   Continuing this discussion on the ParaView email list is probably the best way to iterate to a solid suggestion.

Hope this helps.

Stephen
