### ISSUE TITLE
Unusual thousands separators

### ISSUE THREAD

**Issue by msmolens** [Kitware/paraview-glance#144]
The thousands separator in the Information panel is a space. Typically it is a comma or a period, depending on the localization:
![information](https://user-images.githubusercontent.com/7122091/42600873-e11ec1b6-8531-11e8-82fb-6e68d80f0598.png)

The thousands separator in the Rendering panel is a single quotation mark. Again, it's typically a comma or a period:
![rendering](https://user-images.githubusercontent.com/7122091/42600868-dd6f4d74-8531-11e8-97a2-6bb941111118.png)

**Comment by floryst** [comment]
Moving my comments from the PR to here, since I won't close this for now.

Realistically we should have some localization support since using spaces is French convention. Since we don't have that yet, the thousands separator should at least be consistent. Since the FPS info is from vtk.js, changes need to be made there to support an arbitrary and/or localized separator.
