### ISSUE TITLE
Window level not adjustable

### ISSUE THREAD

**Issue by samuelgerber** [Kitware/paraview-glance#217]
The window level of this image cannot be adjusted properly:
https://data.kitware.com/api/v1/item/5bc9ed218d777f06b92dad3d/download?contentDisposition=inline

When adjusting the window level in the slice view glance complains with:

ParaViewGlance: 2.8.0
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

```
InternalError: too much recursion,InternalError: too much recursion
```

**Comment by jourdain** [comment]
Tried on Mac with Chrome and it seems to be fine except that the range seems to be 0 and 1.

**Comment by samuelgerber** [comment]
Yes, try to adjust to something in between and it crashes. Also if you open it with ImageViewer or Slicer you can see that the image has ranges in between.

**Comment by floryst** [comment]
Turns out the step values are explicitly and implicitly set to increments of 1 in vtk.js, as seen [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Proxy/Core/View2DProxy/index.js#L160) and [here](https://github.com/Kitware/vtk-js/blob/master/Sources/Interaction/Manipulators/MouseRangeManipulator/index.js#L30).

I'll make changes to vtk.js to use sub-1 increments and make sure nothing breaks.

**Comment by floryst** [comment]
Refer to https://github.com/Kitware/vtk-js/pull/926 for a fix. I'm not sure if this will fix the recursion error since I haven't seen that so far, but hopefully it does.
