### ISSUE TITLE
Paint: undo fails with multiple labels

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#236]
Create 2 labels
Then paint 1 stroke for Label 0
Then paint 1 stroke for Label 1
Then paint 1 stroke for Label 0
Then paint 1 stroke for Label 1
...

Click multiple times on Undo button
-> labelmap labels jumps

**Comment by aylward** [comment]
I have been trying to document that bug.  Nice detective work!  Thanks!

---
Sent via phone.

**Comment by floryst** [comment]
Adding to the reproduction steps: make more than 8 strokes of various colors before hitting undo.

I was confused because I couldn't reproduce this, but now I have after more than 8 strokes. Right now the history buffer supports up to 8 strokes (up to 32 and even 64 strokes technically), so there's a bug in how I track colors of old strokes.
