### ISSUE TITLE
Paint: 1st green disk is not visible

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#237]
Click on "Enable Painting"
Then mouse down on a 2D view
Then quick move the mouse while keeping the mouse down
-> Problem 1: There is no green disk visible under the area where the mouse button was pressed down
Few green disks are displayed 
Release the mouse button
-> Problem 2: The entire stroke between the press and release is correctly painted (area is different than the green disks)

**Comment by floryst** [comment]
Ah, nice catch. I had initially disabled the first green disk because of issues making inadvertent paints when clicking on other views (e.g. in quad view). I will add the 1st green disk back and find another way to fix this.

As for the few green disks issue, that's a limitation of mouse sampling. I've tested mouse event sampling with a barebones js example, and get the same issue. It's worth noting that Slicer's paintbrush exhibits the same behavior, though maybe not as severe as the sampling rate I can get in the browser.
