### ISSUE TITLE
how to use  proxyFilter.js?

### ISSUE THREAD

**Issue by KevinJJH** [Kitware/paraview-glance#333]
Hi,can you tell me how to use proxyFilter.js? now I need to use WindowedSincPolyDataFilter or ImageMarchingCubes,but I don't know how to use it in this project. thx

**Comment by floryst** [comment]
@jourdain Do you know how proxyFilter is handled? I forget, and would need to look around for this.

**Comment by KevinJJH** [comment]
take a look, you defined proxyFilter but never use it
Thanks for your help!

**Comment by KevinJJH** [comment]
> @jourdain Do you know how proxyFilter is handled? I forget, and would need to look around for this.

take a look, you defined proxyFilter but never use it
Thanks for your help!

**Comment by floryst** [comment]
Ah, I looked through it and now see what happened. I deleted `proxyFilter` references since we weren't using that anymore (i.e. we don't have that exposed in the current UI). Take a look [here](https://github.com/Kitware/paraview-glance/blob/35d723cc77cfbf8707be68977b2a036ab7cd96e5/src/config/proxy.js#L52). You can add it back in as a Source. Then, when you want to run your image through the Contour filter, you do:
```
const contourSource = proxyManager.createProxy('Sources', 'Contour', { name: '', ... });
contourSource.setInputProxy(myImageSource);
```
And don't forget to re-add [Contour as a vtkImageData](https://github.com/Kitware/paraview-glance/blob/35d723cc77cfbf8707be68977b2a036ab7cd96e5/src/config/proxy.js#L137)!

Let me know if you need anymore clarification.

**Comment by KevinJJH** [comment]
if you don't use proxyFilter anymore, how can you run your image through the filter? is there any other way to use filter in this project?I want to use WindowedSincPolyDataFilter to make image more smooth,I think  ImageMarchingCubes 
I tried,but It doesn't work. ERROR:Invalid or missing input.
please check my code
`   const contourSource = this.$proxyManager.createProxy('Sources', 'Contour');//this doesn't work,ERROR:Invalid or missing input.
     contourSource.setInputProxy(this.$proxyManager.getProxyById(this.activeSourceId));`

**Comment by floryst** [comment]
The median filter currently in Glance uses [itk.js](https://github.com/InsightSoftwareConsortium/itk-js/) to run the algorithm.

As for your issue, you should be able to get it to work via:
```
const contourSource = this.$proxyManager.createProxy('Sources', 'Contour', {
  inputProxy: <your proxy here>,
});
```

I'm surprised that you get an invalid input error on createProxy. I'll take a look.

**Comment by KevinJJH** [comment]
thx, now it work.but when I do:
`const contourSource = this.$proxyManager.createProxy('Sources', 'Contour',{inputProxy:myProxy});
                
  this.$nextTick(() => {
                    contourSource.setComputeNormals(true)
                  });`
I am confused why it doesn't have any change on my window. I would like to use WindowedSincPolyDataFilter in the currentUI, should I write another filter like proxyFilter?
![WechatIMG6](https://user-images.githubusercontent.com/29230971/82009712-a4aeaa00-96a2-11ea-91df-f32de7aeb25c.png)
I try to use it this way but failed

**Comment by KevinJJH** [comment]
Hi,are you still there? I need more clarification

**Comment by floryst** [comment]
Hi! this dropped off my radar. Right now Glance needs a bit of tweaking before you can comfortably use filters, since those were unfortunately not expanded upon after testing it early on. I can quickly outline a few things that would need to be changed:
- Parts of Glance currently filter on TrivialProducer typed proxies, meaning your Contour proxy won't be seen. Wherever you find the string "TrivialProducer" is likely where you will need to add an OR conditional to also check for the "Contour" type. For example, see [Datasets/script.js](https://github.com/Kitware/paraview-glance/blob/master/src/components/core/Datasets/script.js#L87). In this function, I only filter on datasets that are of type "TrivialProducer". You would need to add a `|| s.getProxyName() === 'Contour'` and change the `.filter(...)` line to get your contour to show up on the side.
- Filters probably won't correctly show up with usable properties like "Sample Distance" and "Edge Gradient" since we don't have any auto-generated UI. For Contour filter, look at `proxyPropertyMapping`, and note how they line up with the "name" property in the ui section. (A side note: you should make the Contour ui property look something more like what is in `proxyUI.js`, since that is old code that doesn't have meaning in Glance anymore.) These properties get usable UI via control components like [Representation/script.js](https://github.com/Kitware/paraview-glance/blob/master/src/components/controls/Representation/script.js) and [Representation/template.html](https://github.com/Kitware/paraview-glance/blob/master/src/components/controls/Representation/template.html). Once you define them (e.g. a "computeNormals" property that gets associated with a checkbox in `template.html`), then your filter will have the beginnings of a usable UI.

This requires a bit more plumbing work going into Glance, and I currently don't have available time to provide concrete code. However, I'll try to provide guidance so you can get this to work. :)

**Comment by floryst** [comment]
Addendum: You probably are better off doing something similar to how [MedianFilter](https://github.com/Kitware/paraview-glance/blob/master/src/components/tools/MedianFilter/script.js) is done. That way, your filtered datasets will automatically show up in Glance without modifying internal plumbing.

**Comment by KevinJJH** [comment]
Thank you,I will try. Talk later
