### ISSUE TITLE
Efficient Labelmap

### ISSUE THREAD

**Issue by thomas-beznik** [Kitware/paraview-glance#335]
Hello,

I am labelling big DICOM files (e.g. 512x512x609 and bigger) using paraview-glance and it is quite slow. I noticed that in the paint tool, a label map of the size of the image is created at initialization. The volume that I am segmenting is quite small compared to the full image; I was thus thinking that there could be a much more efficient way to handle this label map, for example by storing it as a sparse array.

My questions are thus:

- Is this something you already considered?
- Is it feasible to implement such feature without re-writing too much of the app?
- What are the main components that will need to be adapted?
- Do you see another way of efficiently handling these label maps?

Thank you!

**Comment by floryst** [comment]
Hi! Rewriting to use a sparse array should be doable without rewriting much of the app at all. I believe the majority of the work would be done in vtk.js. Specifically, we would need to create some means of storing sparse images (i.e. as an extension to vtkImageData), and then make some changes to vtkPaintFilter so that we write each voxel to your sparse image object.

It would be nice to have other representations other than an image, but right now there isn't any efforts going towards that direction. The paint filter is understandably slow for large images, and I am open to ideas for improving the painting to be more performant under those conditions.

**Comment by thomas-beznik** [comment]
Thank you! I will start working on this and ask my questions on vtk.js then!
