### ISSUE TITLE
How to export scrollable slices from ParaView?

### ISSUE THREAD

**Issue by liangwang0734** [Kitware/paraview-glance#349]
In `Tooth-quad.glance`, for example, you can adjust slices by using x,y,z slides. How do I export such data in the vtkjs format through the Export Scene feature of ParaView?

PS: Shall I post help questions here, or on http://discourse.paraview.org/?

**Comment by jourdain** [comment]
Those are specific capabilities of ParaViewGlance. The export of ParaViewGlance should be the way to go while using remote dataset, or we need to improve the Glance export to better handle dataset.

**Comment by liangwang0734** [comment]
Sorry, I'm a little confused.

> Those are specific capabilities of ParaViewGlance.
> The export of ParaViewGlance should be the way to go while using remote dataset,

Does this refer to opening the full data directly within Glance?

> or we need to improve the Glance export to better handle dataset.

Does this refer to the `Export Scene` feature of the original ParaView?

------------
I did figure out a workflow that kind of work for me:
- Load the full data into ParaView.
- Resample onto a uniform grid.
- Save the resampled data into a `vti` data that is supported by Glance.
- Load the data in Glance, and the `Slice` option is available now.
- Cons: The original nonuniform/unstructured grid info is lost. This is fine for me since these are for quick-preview anyway.

Previously, my workflow was:
- Load the full data into ParaView.
- Do the rendering wanted, including slicing.
  - I would not be able to scan through the slices.
- Use `Export Scene` to generate a `vtkjs` file.
- Open the generated `vtkjs` file.
- Cons: Can not to interactive slice since all slices are pre-computed.

**Comment by jourdain** [comment]
ParaView `Export Scene` is really meant to export a scene as-is (geometry / polydata) and only look at other fields on the same geometry.

The ParaViewGlance export aims to provide full capture of a given visual state. And since you are looking at slicing through vtkImageData, you really want to provide the data to glance and let the UI of glance do the rest.

**Comment by liangwang0734** [comment]
> ParaView `Export Scene` is really meant to export a scene as-is (geometry / polydata) and only look at other fields on the same geometry.
> 
> The ParaViewGlance export aims to provide full capture of a given visual state. And since you are looking at slicing through vtkImageData, you really want to provide the data to glance and let the UI of glance do the rest.

Thank you @jourdain . Yes, it took a while to realize this.

Now I'm exporting the data into `vti` data since it appears to me Glance cannot read vtkRectilinear or vtkUnstructured data, and perhaps cannot slice vtkPolyData. This not a big issue, though.

**Comment by jourdain** [comment]
Glance and vtkjs don't really handle anything else than vtkPolydata and vtkImageData. 
Also if you were to slice a polydata you will endup with lines rather than a surface since polydata is the surface mesh as opposed to the 3D cells that you can find in unstructured grid or rectilinear grid. 

One thing that you could do is create many slices of your data in PV and have the user in Glance toggle them on/off.
That way you have a full polydata based scene that the user can interact with. But you don't get the possible benefit of the multi-slice view that Glance has which is widely used in a medical context.

**Comment by liangwang0734** [comment]
Thank you for your suggestions, Sebastien. I plan to test both approaches (i.e., pre-slice in ParaView and export vs. export image data in ParaView and slice in Glance).
